apiVersion: flightctl.io/v1beta1
kind: Fleet
metadata:
  name: yodai
spec:
  selector:
    matchLabels:
      fleet: yodai
  template:
    metadata:
      labels:
        fleet: yodai
    spec:
      applications:
        - name: yodai
          appType: compose
          envVars:
            YODAI_INFERENCE_URL: http://inference:8000
            YODAI_LISTEN_ADDR: ":8080"
          inline:
            - path: docker-compose.yaml
              content: |
                services:
                  inference:
                    image: quay.io/sdelacru/yodai-inference:latest
                    devices:
                      - nvidia.com/gpu=all
                    security_opt:
                      - label=disable
                    ports:
                      - "8000:8000"

                  yodai:
                    image: quay.io/sdelacru/yodai:latest
                    ports:
                      - "8080:8080"
                    environment:
                      - YODAI_INFERENCE_URL=${YODAI_INFERENCE_URL}
                      - YODAI_LISTEN_ADDR=${YODAI_LISTEN_ADDR}
                    depends_on:
                      - inference
