FROM golang:1.26-bookworm AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o yodai ./cmd/yodai/

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /build/yodai /usr/local/bin/yodai
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/yodai"]
