services:
  inference:
    image: quay.io/sdelacru/yodai-inference:latest
    devices:
      - nvidia.com/gpu=all
    security_opt:
      - label=disable
    volumes:
      - model-data:/data/models
    ports:
      - "8000:8000"
    environment:
      - ENGINE_DIR=/data/models/engine
      - TOKENIZER_DIR=/data/models/tokenizer

  yodai:
    image: quay.io/sdelacru/yodai:latest
    ports:
      - "8080:8080"
    environment:
      - YODAI_INFERENCE_URL=http://inference:8000
      - YODAI_LISTEN_ADDR=:8080
    depends_on:
      - inference

volumes:
  model-data:
    driver: local
